-- Cloudflare D1 Database Schema for AIUB CS PWA

DROP TABLE IF EXISTS courses;
CREATE TABLE courses (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  credits INTEGER NOT NULL,
  ongoing INTEGER NOT NULL DEFAULT 0,
  completed_topics INTEGER NOT NULL DEFAULT 0,
  total_topics INTEGER NOT NULL DEFAULT 14,
  icon_type TEXT NOT NULL,
  syllabus_json TEXT NOT NULL
);

DROP TABLE IF EXISTS materials;
CREATE TABLE materials (
  id TEXT PRIMARY KEY,
  course_id TEXT NOT NULL,
  course_code TEXT NOT NULL,
  course_title TEXT NOT NULL,
  title TEXT NOT NULL,
  added_time TEXT NOT NULL,
  size TEXT NOT NULL,
  file_type TEXT NOT NULL,
  category TEXT NOT NULL,
  badges_json TEXT NOT NULL,
  is_bookmarked INTEGER DEFAULT 0,
  is_downloaded INTEGER DEFAULT 0,
  pages_count INTEGER DEFAULT 1,
  r2_key TEXT,
  document_content_json TEXT,
  FOREIGN KEY (course_id) REFERENCES courses(id)
);

DROP TABLE IF EXISTS announcements;
CREATE TABLE announcements (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  desc TEXT NOT NULL,
  unread INTEGER DEFAULT 1
);

-- Seed All Official 96 AIUB CS Courses into Cloudflare D1
INSERT INTO courses (id, code, title, category, credits, ongoing, completed_topics, total_topics, icon_type, syllabus_json) VALUES
('csc-1101', 'CSC 1101', 'Introduction to Computer Studies', 'Core CS', 3, 0, 0, 10, 'book', '["Computer Organization", "Operating System Basics", "Binary Arithmetic", "Software Systems"]'),
('csc-1102', 'CSC 1102', 'Introduction to Programming Language', 'Core CS', 3, 0, 0, 12, 'code', '["C Syntax", "Variables & Operators", "Control Flow & Loops", "Functions & Pointers", "Arrays & Structures"]'),
('csc-1103', 'CSC 1103', 'Introduction to Programming Language Lab', 'Core CS', 1, 0, 0, 12, 'code', '["C Programming Lab Experiments", "Debugging & Code Execution"]'),
('csc-1204', 'CSC 1204', 'Discrete Mathematics', 'Core CS', 3, 0, 0, 12, 'math', '["Propositional Logic", "Sets & Relations", "Induction", "Combinatorics", "Graph Theory"]'),
('csc-1205', 'CSC 1205', 'Object Oriented Programming 1', 'Core CS', 3, 0, 0, 14, 'code', '["Java Syntax", "Classes & Objects", "Inheritance", "Polymorphism", "Encapsulation"]'),
('csc-2106', 'CSC 2106', 'Data Structure', 'Core CS', 3, 0, 0, 14, 'cpu', '["Arrays & Stacks", "Queues & Linked Lists", "Binary Trees", "Heap & Hashing", "Sorting Algorithms"]'),
('csc-2107', 'CSC 2107', 'Data Structure Lab', 'Core CS', 1, 0, 0, 14, 'cpu', '["Data Structures C++ Lab Implementation"]'),
('csc-2108', 'CSC 2108', 'Introduction to Database', 'Core CS', 3, 1, 0, 14, 'database', '["Relational Model", "SQL DDL/DML", "ER Diagrams", "Normalization 1NF-BCNF", "Indexing"]'),
('csc-2209', 'CSC 2209', 'Object Oriented Analysis and Design', 'Core CS', 3, 0, 0, 12, 'code', '["Requirements Modeling", "UML Class & Use Case Diagrams", "Sequence Diagrams", "Design Patterns"]'),
('csc-2210', 'CSC 2210', 'Object Oriented Programming 2', 'Core CS', 3, 1, 0, 14, 'code', '["Advanced OOP Concepts", "GUI & Event Handling", "Multithreading", "Database Connectivity"]'),
('csc-2211', 'CSC 2211', 'Algorithms', 'Core CS', 3, 0, 0, 16, 'cpu', '["Asymptotic Growth", "Divide & Conquer", "Greedy Algorithms", "Dynamic Programming", "Graph Search"]'),
('csc-3112', 'CSC 3112', 'Software Engineering', 'Software Engineering', 3, 1, 0, 12, 'code', '["SDLC Models", "Agile Methodologies", "Software Verification", "Software Architecture"]'),
('csc-3113', 'CSC 3113', 'Theory of Computation', 'Core CS', 3, 0, 0, 12, 'math', '["Finite Automata DFA/NFA", "Regular Expressions", "Context-Free Grammars", "Turing Machines", "Decidability"]'),
('csc-3214', 'CSC 3214', 'Operating Systems', 'Core CS', 3, 0, 0, 14, 'cpu', '["Process Scheduling", "Inter-Process Communication", "Deadlocks", "Memory Paging", "File Systems"]'),
('csc-3215', 'CSC 3215', 'Web Technologies', 'Software Engineering', 3, 0, 0, 14, 'code', '["HTML5 & CSS3", "JavaScript & DOM", "Server Programming", "REST APIs", "Web Security"]'),
('csc-3216', 'CSC 3216', 'Compiler Design', 'Core CS', 3, 0, 0, 14, 'code', '["Lexical Analysis", "Parsing LL/LR", "Semantic Analysis", "Intermediate Representation", "Optimization"]'),
('csc-3217', 'CSC 3217', 'Artificial Intelligence and Expert System', 'Data Science & AI', 3, 0, 0, 14, 'ai', '["Heuristic Search", "Minimax & Alpha-Beta", "Knowledge Representation", "Rule-Based Expert Systems", "Machine Learning"]'),
('csc-4118', 'CSC 4118', 'Computer Graphics', 'Core CS', 3, 0, 0, 12, 'code', '["2D/3D Transformations", "Rasterization Algorithms", "Clipping Algorithms", "Shading & Lighting", "OpenGL Pipeline"]'),
('csc-4180', 'CSC 4180', 'Introduction to Data Science', 'Data Science & AI', 3, 0, 0, 12, 'ai', '["Data Preprocessing", "Exploratory Data Analysis", "Statistical Models", "Supervised Learning", "Python Data Stack"]'),
('csc-4181', 'CSC 4181', 'Advance Database Management Systems', 'Data Science & AI', 3, 0, 0, 12, 'database', '["Distributed DBMS", "NoSQL Storage", "Query Optimization", "Concurrency Tuning", "Data Warehousing"]'),
('csc-4182', 'CSC 4182', 'Human Computer Interaction', 'Data Science & AI', 3, 0, 0, 10, 'code', '["User-Centered Design", "UI Wireframing & Prototyping", "Usability Evaluation", "Interaction Models"]'),
('csc-4183', 'CSC 4183', 'Cyber Laws & Information Security', 'Data Science & AI', 3, 0, 0, 10, 'network', '["Information Security Policies", "Cyber Ethics & Laws", "Digital Rights", "Data Privacy Regulations"]'),
('csc-4230', 'CSC 4230', 'Bioinformatics', 'Data Science & AI', 3, 0, 0, 10, 'ai', '["DNA Sequence Alignment", "BLAST Algorithms", "Phylogenetics", "Gene Expression Profiling"]'),
('csc-4231', 'CSC 4231', 'Parallel Computing', 'Core CS', 3, 0, 0, 12, 'cpu', '["Parallel Hardware Architectures", "MPI & OpenMP Programming", "GPU Computing (CUDA)", "Parallel Speedup Models"]'),
('csc-4232', 'CSC 4232', 'Machine Learning', 'Data Science & AI', 3, 0, 0, 14, 'ai', '["Linear & Logistic Regression", "Decision Trees & Ensembles", "Support Vector Machines", "Clustering & PCA", "Neural Networks"]'),
('csc-4233', 'CSC 4233', 'Natural Language Processing', 'Data Science & AI', 3, 0, 0, 12, 'ai', '["Text Tokenization & Parsing", "N-gram Models", "Word Embeddings", "RNNs & LSTMs", "Transformer Models"]'),
('csc-4251', 'CSC 4251', 'Image Processing', 'Data Science & AI', 3, 0, 0, 12, 'ai', '["Digital Image Fundamentals", "Spatial & Frequency Filtering", "Image Restoration", "Edge Detection", "Morphological Processing"]'),
('csc-4254', 'CSC 4254', 'Computer Vision & Pattern Recognition', 'Data Science & AI', 3, 0, 0, 12, 'ai', '["Image Features & Descriptors", "Convolutional Networks (CNNs)", "Object Detection (YOLO)", "Pattern Recognition Classifiers"]'),
('csc-4285', 'CSC 4285', 'Data Warehouse and Data Mining', 'Data Science & AI', 3, 0, 0, 12, 'database', '["ETL Processing", "Star & Snowflake Schemas", "OLAP Cubes", "Association Rule Mining", "Clustering Algorithms"]'),
('csc-4160', 'CSC 4160', 'Software Requirement Engineering', 'Software Engineering', 3, 0, 0, 10, 'code', '["Elicitation Techniques", "SRS Documentation", "Requirement Validation", "Traceability Matrices"]'),
('csc-4261', 'CSC 4261', 'Advanced Programming in Web Technologies', 'Software Engineering', 3, 0, 0, 12, 'code', '["Single Page Applications (React)", "TypeScript & State Management", "Next.js SSR", "GraphQL APIs"]'),
('csc-4262', 'CSC 4262', 'Programming in Python', 'Software Engineering', 3, 0, 0, 10, 'code', '["Python Fundamentals", "Data Structures & OOP", "File I/O & Modules", "Web Development with Flask/Django"]'),
('csc-4263', 'CSC 4263', 'Advanced Programming with JAVA', 'Software Engineering', 3, 0, 0, 12, 'code', '["Spring Boot Framework", "Hibernate & JPA", "REST Microservices", "Spring Security"]'),
('csc-4264', 'CSC 4264', 'Advanced Programming with .NET', 'Software Engineering', 3, 0, 0, 12, 'code', '["C# & ASP.NET Core", "Entity Framework Core", "LINQ Queries", "Web API Microservices"]'),
('csc-4270', 'CSC 4270', 'Software Development Project Management', 'Software Engineering', 3, 0, 0, 10, 'code', '["Project Scheduling & Estimation", "Risk Management", "Agile & Scrum Practices", "Team Leadership"]'),
('csc-4271', 'CSC 4271', 'Software Quality and Testing', 'Software Engineering', 3, 0, 0, 10, 'code', '["Unit Testing", "Integration & System Testing", "Automated QA Tools (Selenium)", "Code Coverage Analysis"]'),
('csc-4272', 'CSC 4272', 'Mobile Application Development', 'Software Engineering', 3, 0, 0, 14, 'code', '["Mobile UI Patterns", "Cross-Platform Frameworks", "Local Storage & State", "Mobile API Integration"]'),
('csc-4273', 'CSC 4273', 'Software Architecture & Design Patterns', 'Software Engineering', 3, 0, 0, 12, 'code', '["Creational, Structural & Behavioral Patterns", "Clean Architecture", "Microservices vs Monoliths", "SOLID Principles"]'),
('eee-2101', 'EEE 2101', 'Basic Mechanical Engineering', 'Computer Hardware & COE', 3, 0, 0, 10, 'science', '["Statics & Dynamics", "Thermodynamics Principles", "Fluid Mechanics", "Mechanical Tools"]'),
('eee-2103', 'EEE 2103', 'Electronic Devices', 'Computer Hardware & COE', 3, 0, 0, 12, 'cpu', '["Semiconductor Diodes", "BJT Transistors", "FET & MOSFET Devices", "Amplifier Circuits"]'),
('eee-2104', 'EEE 2104', 'Electronic Devices Lab', 'Computer Hardware & COE', 1, 0, 0, 12, 'cpu', '["Electronic Devices Experiments"]'),
('eee-2108', 'EEE 2108', 'Introduction to Electrical Circuits', 'Computer Hardware & COE', 3, 0, 0, 12, 'cpu', '["Ohm Law & Kirchhoff Laws", "Mesh & Nodal Analysis", "Network Theorems", "AC Circuit Analysis"]'),
('eee-2109', 'EEE 2109', 'Introduction to Electrical Circuits Lab', 'Computer Hardware & COE', 1, 0, 0, 12, 'cpu', '["Electrical Circuits Experiments"]'),
('eee-2213', 'EEE 2213', 'Signals and Linear Systems', 'Computer Hardware & COE', 3, 0, 0, 12, 'science', '["Continuous & Discrete Signals", "LTI System Properties", "Fourier Series & Transform", "Laplace Transform"]'),
('eee-2216', 'EEE 2216', 'Engineering Ethics', 'Computer Hardware & COE', 3, 0, 0, 8, 'book', '["Engineering Professional Codes", "Safety & Liability", "Environmental Ethics", "Intellectual Property"]'),
('eee-3101', 'EEE 3101', 'Digital Logic and Circuits', 'Computer Hardware & COE', 3, 0, 0, 12, 'cpu', '["Boolean Algebra & Gate Minimization", "Karnaugh Maps", "Combinational Logic", "Sequential Logic & Flip-Flops", "Counters & Registers"]'),
('eee-3103', 'EEE 3103', 'Digital Signal Processing (DSP)', 'Computer Hardware & COE', 3, 0, 0, 12, 'science', '["Discrete Fourier Transform (DFT)", "Fast Fourier Transform (FFT)", "IIR & FIR Filter Design", "DSP Processor Hardware"]'),
('eee-4209', 'EEE 4209', 'Telecommunications Engineering', 'Computer Hardware & COE', 3, 0, 0, 12, 'network', '["Modulation Techniques AM/FM", "Digital Transmission PCM/ASK/FSK", "Cellular Networks 4G/5G", "Satellite Communications"]'),
('eee-4217', 'EEE 4217', 'VLSI Circuit Design', 'Computer Hardware & COE', 3, 0, 0, 12, 'cpu', '["CMOS Logic Design", "Silicon Fabrication Steps", "Layout & Mask Generation", "Verilog Synthesis"]'),
('eee-4233', 'EEE 4233', 'Digital Design with System Verilog, VHDL & FPGAs', 'Computer Hardware & COE', 3, 0, 0, 12, 'cpu', '["Hardware Description Languages (VHDL/Verilog)", "FPGA Architectures", "RTL Simulation", "Synthesis & Placement"]'),
('eee-4241', 'EEE 4241', 'Industrial Electronics, Drives & Instrumentation', 'Computer Hardware & COE', 3, 0, 0, 10, 'cpu', '["Power Electronics (Thyristors/Triacs)", "Motor Speed Control Drives", "Sensors & Instrumentation", "PLC Controllers"]'),
('coe-3101', 'COE 3101', 'Data Communication', 'Computer Hardware & COE', 3, 0, 0, 12, 'network', '["Data Transmission Fundamentals", "Multiplexing Techniques (TDM/FDM)", "Error Detection & Correction", "Data Link Protocols"]'),
('coe-3102', 'COE 3102', 'Microprocessor and Embedded Systems', 'Computer Hardware & COE', 3, 0, 0, 12, 'cpu', '["8086 Microprocessor Architecture", "Assembly Language Programming", "Interrupt Processing & Memory Interfacing", "ARM Microcontroller Programming"]'),
('coe-3203', 'COE 3203', 'Computer Organization & Architecture', 'Computer Hardware & COE', 3, 0, 0, 12, 'cpu', '["CPU Datapath & Control Unit", "Instruction Set Architecture (RISC/CISC)", "Cache Memory & Virtual Memory", "Pipelining & Parallelism"]'),
('coe-3204', 'COE 3204', 'Computer Networks', 'Computer Hardware & COE', 3, 0, 0, 14, 'network', '["OSI & TCP/IP Reference Models", "IP Subnetting IPv4/IPv6", "Routing Protocols RIP/OSPF/BGP", "TCP Congestion Control"]'),
('coe-4140', 'COE 4140', 'Advanced Operating Systems', 'Computer Hardware & COE', 3, 0, 0, 12, 'cpu', '["Distributed OS Kernels", "Distributed Mutual Exclusion", "Fault Tolerance & Replication", "Virtualization Technologies"]'),
('coe-4141', 'COE 4141', 'Advanced Computer Networks', 'Computer Hardware & COE', 3, 0, 0, 12, 'network', '["Software-Defined Networking (SDN)", "Network Function Virtualization (NFV)", "High-Speed Packet Switching", "QoS Architectures"]'),
('coe-4142', 'COE 4142', 'Network Resource Management & Organization', 'Computer Hardware & COE', 3, 0, 0, 10, 'network', '["Traffic Modeling & Queuing Theory", "Bandwidth Allocation Models", "Network Management Protocols (SNMP)"]'),
('coe-4143', 'COE 4143', 'Digital System Design', 'Computer Hardware & COE', 3, 0, 0, 12, 'cpu', '["RTL Design & State Machine Synthesis", "VHDL/Verilog Design Verification", "ASIC & FPGA Design Workflows"]'),
('coe-4250', 'COE 4250', 'Simulation and Modelling', 'Computer Hardware & COE', 3, 0, 0, 10, 'science', '["Discrete-Event Simulation", "Random Number Generators", "Model Validation Techniques", "Monte Carlo Methods"]'),
('coe-4252', 'COE 4252', 'Network Security', 'Computer Hardware & COE', 3, 0, 0, 12, 'network', '["Symmetric & Public-Key Cryptography", "TLS/SSL Protocols", "Firewalls & IPS Systems", "Wireless Network Security"]'),
('coe-4253', 'COE 4253', 'Wireless Sensor Network', 'Computer Hardware & COE', 3, 0, 0, 10, 'network', '["Sensor Node Hardware Architecture", "WSN MAC & Routing Protocols", "Zigbee & IoT Communication Standards", "Energy Conservation Protocols"]'),
('coe-4255', 'COE 4255', 'Robotics Engineering', 'Computer Hardware & COE', 3, 0, 0, 12, 'cpu', '["Kinematics & Dynamics of Robot Arms", "Sensors & Actuators", "Path Planning & Navigation (SLAM)", "Robot Operating System (ROS)"]'),
('mat-1102', 'MAT 1102', 'Differential Calculus and Coordinate Geometry', 'Math & Science', 3, 0, 0, 12, 'math', '["Limits & Continuity", "Derivatives & Applications", "Partial Derivatives", "2D & 3D Geometry"]'),
('mat-1205', 'MAT 1205', 'Integral Calculus and Ordinary Differential Equations', 'Math & Science', 3, 0, 0, 12, 'math', '["Definite & Indefinite Integrals", "Multiple Integrals", "1st Order ODEs", "Higher Order Differential Equations"]'),
('mat-2101', 'MAT 2101', 'Complex Variables, Laplace and Z-transformations', 'Math & Science', 3, 0, 0, 12, 'math', '["Analytic Complex Functions", "Cauchy-Riemann Equations", "Laplace Transform", "Z-Transform Applications"]'),
('mat-2202', 'MAT 2202', 'Matrices, Vectors and Fourier Analysis', 'Math & Science', 3, 0, 0, 12, 'math', '["Matrix Algebra & Eigenvalues", "Vector Differential Calculus", "Fourier Series & Integrals", "PDE Fundamentals"]'),
('mat-3101', 'MAT 3101', 'Numerical Methods for Science and Engineering', 'Math & Science', 3, 0, 0, 12, 'math', '["Root Finding Methods", "Numerical Integration (Simpson/Trapezoidal)", "System of Linear Equations", "ODE Numerical Solvers"]'),
('mat-3103', 'MAT 3103', 'Computational Statistics and Probability', 'Math & Science', 3, 0, 0, 12, 'math', '["Probability Distributions", "Bayesian Probability", "Hypothesis Testing", "Regression & Correlation"]'),
('csc-4125', 'CSC 4125', 'Computer Science Mathematics', 'Math & Science', 3, 0, 0, 10, 'math', '["Number Theory for Cryptography", "Abstract Algebra Groups/Rings", "Vector Spaces & Matrix Factorizations"]'),
('csc-4126', 'CSC 4126', 'Basic Graph Theory', 'Math & Science', 3, 0, 0, 10, 'math', '["Graph Isomorphism", "Eulerian & Hamiltonian Graphs", "Planar Graphs & Coloring", "Network Flows"]'),
('csc-4127', 'CSC 4127', 'Advanced Algorithm Techniques', 'Core CS', 3, 0, 0, 12, 'cpu', '["Amortized Analysis", "Randomized Algorithms", "Approximation Algorithms", "NP-Hard Problem Reductions"]'),
('csc-4128', 'CSC 4128', 'Linear Programming', 'Math & Science', 3, 0, 0, 10, 'math', '["Simplex Method", "Duality Theory & Sensitivity Analysis", "Integer Linear Programming", "Transportation Problems"]'),
('phy-1101', 'PHY 1101', 'Physics-1', 'Math & Science', 3, 0, 0, 10, 'science', '["Vectors & Motion", "Work, Energy & Momentum", "Rotational Mechanics", "Fluid Statics"]'),
('phy-1102', 'PHY 1102', 'Physics 1 Lab', 'Math & Science', 1, 0, 0, 10, 'science', '["Physics Lab Experiments 1"]'),
('phy-1203', 'PHY 1203', 'Physics 2', 'Math & Science', 3, 0, 0, 10, 'science', '["Electrostatics & Gauss Law", "Magnetism & Ampere Law", "Electromagnetic Waves", "Optics & Quantum Physics"]'),
('phy-1204', 'PHY 1204', 'Physics 2 Lab', 'Math & Science', 1, 0, 0, 10, 'science', '["Physics Lab Experiments 2"]'),
('chem-1101', 'Chem 1101', 'Chemistry', 'Math & Science', 3, 0, 0, 10, 'science', '["Atomic Structure & Chemical Bonding", "Thermochemistry", "Electrochemistry", "Chemical Kinetics"]'),
('bae-2101', 'BAE 2101', 'Computer Aided Design & Drafting Lab', 'Math & Science', 1, 0, 0, 8, 'science', '["AutoCAD 2D Drafting", "3D Modeling & Orthographic Projections"]'),
('eng-1101', 'ENG 1101', 'English Reading Skills and Public Speaking', 'General & Business', 3, 0, 0, 10, 'book', '["Reading Comprehension", "Vocabulary Enhancement", "Public Speaking Principles", "Speech Delivery"]'),
('eng-1202', 'ENG 1202', 'English Writing Skills and Communication', 'General & Business', 3, 0, 0, 10, 'book', '["Essay & Report Writing", "Grammar & Composition", "Business Email Protocols"]'),
('eng-2103', 'ENG 2103', 'Business Communication', 'General & Business', 3, 0, 0, 10, 'book', '["Corporate Presentation Skills", "Meeting Minutes & Proposal Writing", "Cross-Cultural Communication"]'),
('bba-1102', 'BBA 1102', 'Principles of Accounting', 'General & Business', 3, 0, 0, 10, 'book', '["Accounting Cycle", "Financial Statements", "Balance Sheets & Cash Flow Statements"]'),
('mgt-3202', 'MGT 3202', 'Engineering Management', 'General & Business', 3, 0, 0, 10, 'book', '["Organizational Behavior", "Human Resource Management", "Engineering Economics", "Project Risk Management"]'),
('eco-3150', 'ECO 3150', 'Principles of Economics', 'General & Business', 3, 0, 0, 10, 'book', '["Microeconomics Demand & Supply", "Market Structures", "Macroeconomics Indicators (GDP, Inflation)"]'),
('bas-2101', 'BAS 2101', 'Bangladesh Studies', 'General & Business', 3, 0, 0, 8, 'book', '["History & Liberation War of Bangladesh", "Constitution & Governance", "Economy & Socio-Cultural Development"]'),
('mis-3101', 'MIS 3101', 'Management Information Systems', 'General & Business', 3, 0, 0, 10, 'book', '["Information Systems in Global Business", "Enterprise Systems", "Database & Knowledge Management"]'),
('mis-4007', 'MIS 4007', 'Digital Marketing', 'General & Business', 3, 0, 0, 10, 'book', '["SEO & SEM Strategies", "Social Media Analytics", "Content Marketing", "Digital Ad Campaigns"]'),
('mis-4011', 'MIS 4011', 'Enterprise Resource Planning', 'General & Business', 3, 0, 0, 10, 'book', '["ERP Architecture & Modules", "SAP / Oracle ERP Implementations", "Business Process Reengineering"]'),
('mis-4012', 'MIS 4012', 'E-Commerce, E-Governance & E-Series', 'General & Business', 3, 0, 0, 10, 'book', '["E-Commerce Models B2B/B2C", "Payment Gateways & Security", "E-Governance Architectures"]'),
('mis-4014', 'MIS 4014', 'Business Intelligence and Decision Support System', 'General & Business', 3, 0, 0, 10, 'book', '["BI Frameworks", "Executive Dashboards", "Decision Support Algorithms", "Data Visualization"]'),
('csc-4144', 'CSC 4144', 'Multimedia Systems', 'Software Engineering', 3, 0, 0, 10, 'code', '["Audio/Video Compression Algorithms", "JPEG/MPEG Standards", "Streaming Protocols"]'),
('csc-4197', 'CSC 4197', 'Research Methodology', 'General & Business', 3, 0, 0, 8, 'book', '["Literature Survey", "Hypothesis Design", "Data Collection & Statistics", "Paper Writing & Citation"]'),
('csc-4298', 'CSC 4298', 'Thesis/Project', 'General & Business', 6, 1, 0, 6, 'code', '["Thesis Proposal Defense", "System Architecture & Implementation", "Experimental Evaluation", "Final Defense"]'),
('csc-4299', 'CSC 4299', 'Internship', 'General & Business', 3, 0, 0, 1, 'book', '["Industry Software Engineering Placement", "Professional Report Submission & Defense"]');
